FirebaseError: Firebase: Error (auth/unauthorized-domain). It will be fixed but now we should proceed to the admin panel for uploading anime and we can upload anime or movie by tmdb api you know the api and it will also import season and episode from tmdb and anime all details should be good and also genrate genre , category in admin panel and user id management and many features and admin email is - ninjax.desi@gmail.com so he will the admin and only he can access